services:
  - type: web
    name: astrolog-web
    runtime: python
    region: frankfurt
    buildCommand: bash build_render.sh
    startCommand: gunicorn app.wsgi:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: astrolog-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: TOKEN_CONTRACT_ADDRESS
        value: 0xAf6087a1A730DAb2CA8d42dca7893c22fDBA683d
      - key: TOKEN_RECEIVER_ADDRESS
        value: 0x917544120060Feb4571CdB14dBCC1e4d8005c218
      - key: PYTHONUNBUFFERED
        value: 'true'
  
  - type: cron
    name: astrolog-horoscope-generator
    runtime: python
    region: frankfurt
    schedule: "0 0 * * *"  # Run once a day at midnight
    buildCommand: pip install -r requirements.txt
    startCommand: python daily_horoscope_generator.py
    
  - type: redis
    name: astrolog-cache
    ipAllowList: []

databases:
  - name: astrolog-db
    plan: starter
    region: frankfurt
